name: Unpack from DEV

on:
  workflow_dispatch: {}
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'
permissions:
  contents: write 

jobs:
  export-unpack:
    runs-on: windows-latest
    environment: PP-DEV
    steps:
      - uses: actions/checkout@v4

      - name: Install Power Platform CLI
        shell: pwsh
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool
          "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8     

      - name: Auth to PP-DEV
        run: |
          pac auth create --url $env:PP_DEV_URL `
            --tenant $env:PP_TENANT_ID `
            --applicationId $env:PP_CLIENT_ID `
            --clientSecret $env:PP_CLIENT_SECRET
        env:
          PP_DEV_URL: ${{ secrets.PP_DEV_URL }}
          PP_TENANT_ID: ${{ secrets.PP_TENANT_ID }}
          PP_CLIENT_ID: ${{ secrets.PP_CLIENT_ID }}
          PP_CLIENT_SECRET: ${{ secrets.PP_CLIENT_SECRET }}

      - name: Export Core (unmanaged)
        run: |
          pac solution export --name CSCore --path solutions/Core/unmanaged/CSCore.zip --managed false --overwrite true

      - name: Unpack Core
        run: |
          pac solution unpack --zipfile solutions/Core/unmanaged/CSCore.zip --folder solutions/Core/src --processCanvasApps

      - name: Export Automate (unmanaged)
        run: |
          pac solution export --name CSAutomation --path solutions/Automate/unmanaged/CSAutomation.zip --managed false --overwrite true

      - name: Unpack Automate
        run: |
          pac solution unpack --zipfile solutions/Automate/unmanaged/CSAutomation.zip --folder solutions/Automate/src --processCanvasApps

      - name: Auto-commit unpacked solutions
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: export & unpack solutions from DEV"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Export Core (managed)
        run: |
          pac solution export --name CSCore --path solutions/Core/managed/Core_managed.zip --managed true --overwrite true

      - name: Export Automate (managed)
        run: |
          pac solution export --name CSAutomation --path solutions/Automate/managed/Automate_managed.zip --managed true --overwrite true

      - name: Upload managed solutions as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: managed-solutions
          path: solutions/**/managed/*.zip