name: Unpack from DEV

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'

jobs:
  export-unpack:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Power Platform CLI
        shell: pwsh
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool
          "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8

      - name: Verify pac
        shell: pwsh
        run: pac --version

      - name: Auth to PP-DEV
        run: |
          pac auth create --url $env:PP_DEV_URL `
            --tenant $env:PP_TENANT_ID `
            --clientId $env:PP_CLIENT_ID `
            --clientSecret $env:PP_CLIENT_SECRET
        env:
          PP_DEV_URL: ${{ secrets.PP_DEV_URL }}
          PP_TENANT_ID: ${{ secrets.PP_TENANT_ID }}
          PP_CLIENT_ID: ${{ secrets.PP_CLIENT_ID }}
          PP_CLIENT_SECRET: ${{ secrets.PP_CLIENT_SECRET }}

      - name: Export Core (unmanaged)
        run: |
          pac solution export --name Core --path solutions/Core/unmanaged/Core.zip --managed false --overwrite true

      - name: Unpack Core
        run: |
          pac solution unpack --zipfile solutions/Core/unmanaged/Core.zip --folder solutions/Core/src --processCanvasApps

      - name: Export Automate (unmanaged)
        run: |
          pac solution export --name Automate --path solutions/Automate/unmanaged/Automate.zip --managed false --overwrite true

      - name: Unpack Automate
        run: |
          pac solution unpack --zipfile solutions/Automate/unmanaged/Automate.zip --folder solutions/Automate/src --processCanvasApps

      - name: Auto-commit unpacked solutions
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: export & unpack solutions from DEV"
