name: Unpack from DEV

on:
  workflow_dispatch: {}
  push:
    branches: [ master ]

jobs:
  export-unpack:
    runs-on: windows-latest
    environment: PP-DEV   # <-- binds secrets.* to the PP-DEV Environment

    steps:
      - uses: actions/checkout@v4

      # Install Power Platform CLI on the runner
      - uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Verify PAC
        shell: pwsh
        run: pac --version

      - name: Auth to PP-DEV (Environment secrets)
        shell: pwsh
        run: |
          pac auth create `
            --url          "${{ secrets.PP_DEV_URL }}" `
            --tenant       "${{ secrets.PP_TENANT_ID }}" `
            --clientId     "${{ secrets.PP_CLIENT_ID }}" `
            --clientSecret "${{ secrets.PP_CLIENT_SECRET }}"
          pac org who

      - name: Prepare solution folders
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path solutions/Core/unmanaged | Out-Null
          New-Item -ItemType Directory -Force -Path solutions/Core/src       | Out-Null
          New-Item -ItemType Directory -Force -Path solutions/Automate/unmanaged | Out-Null
          New-Item -ItemType Directory -Force -Path solutions/Automate/src       | Out-Null

      - name: Export Core (unmanaged)
        shell: pwsh
        run: |
          pac solution export `
            --name Core `
            --path solutions/Core/unmanaged/Core.zip `
            --managed false `
            --overwrite true

      - name: Unpack Core
        shell: pwsh
        run: |
          pac solution unpack `
            --zipfile solutions/Core/unmanaged/Core.zip `
            --folder  solutions/Core/src `
            --processCanvasApps

      - name: Export Automate (unmanaged)
        shell: pwsh
        run: |
          pac solution export `
            --name Automate `
            --path solutions/Automate/unmanaged/Automate.zip `
            --managed false `
            --overwrite true

      - name: Unpack Automate
        shell: pwsh
        run: |
          pac solution unpack `
            --zipfile solutions/Automate/unmanaged/Automate.zip `
            --folder  solutions/Automate/src `
            --processCanvasApps

      - name: Auto-commit unpacked solutions
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: export & unpack solutions from DEV"
